env:
  browser: true
  es6: true
extends: airbnb
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  jsx-quotes:
    - 0
    - prefer-single
  max-len:
    - error
    - 120